php/lib/db/toba_db_postgres7.php
Hecho el cambio en la excepción. 
No lo edité desde el otro pull-request porque github me decía que el archivo estaba en iso8859-1 y que al commitearlo iba a transcodearlo a utf-8.
=> Insert masivo

php/modelo/var/saml_onelogin.ini, php/nucleo/lib/autenticacion/toba_autenticacion_saml_onelogin.php
=>  Agrega parametro usa_proxy_vars

composer.json, php/nucleo/lib/toba_cliente_rdi.php
=>  Pasa el paquete siu/rdi a suggested

php/lib/toba_varios.php, php/modelo/toba_modelo_rest.php, php/nucleo/lib/rest/toba_usuarios_rest_conf.php, php/nucleo/lib/rest/toba_usuarios_rest_ssl.php, php/nucleo/lib/toba_rest.php, php/nucleo/lib/toba_servicio_web_cliente_rest.php
=>  Agrega lectura de config desde env-vars para rest (#82)

php/lib/db/toba_db.php, php/lib/db/toba_db_informix.php, php/lib/db/toba_db_mysql.php, php/lib/db/toba_db_odbc.php, php/lib/db/toba_db_postgres7.php, php/lib/db/toba_db_sqlserver.php, php/nucleo/lib/toba_perfil_datos.php
- Se modifica la ER para quitar comentarios en perfil de datos
- Se separa en cada motor para contemplar variaciones de delimitadores
=> Fix eliminacion comentarios en PD

php/modelo/toba_modelo_instalacion.php, php/modelo/var/saml.ini, php/modelo/var/saml_onelogin.ini, php/nucleo/lib/toba_autenticacion.php
Agrega posibilidad de leer mas atributos del token SAML
=> Lee campos extra en token SAML

composer.json, composer.lock, package.json
Actualiza paquetes para evitar vulnerabilidades
=> Actualizacion de paquetes

php/modelo/toba_modelo_proyecto.php
Pasa la exportacion de membresias de simple a multiple
=>  Mejora en exportacion de membresias

composer.json, composer.lock, package.json, php/nucleo/lib/toba_escapador.php
Fix avisos dependabot y corrige toba_escapador por actualizacion de laminas-escaper
=>  Update dependencias por CVEs 

proyectos/toba_usuarios/metadatos/componentes/toba_ei_formulario/dump_2185.sql, proyectos/toba_usuarios/metadatos_compilados/comp/toba_mc_comp__2185.php, proyectos/toba_usuarios/metadatos_compilados/oper/toba_mc_oper__3432.php, proyectos/toba_usuarios/php/lib/rest_arai_usuarios.php, proyectos/toba_usuarios/php/usuarios/ci_editor.php, proyectos/toba_usuarios/php/usuarios/ei_form_basica.php
- Corrige problema de desactivacion de efs  - Corrige problema de obligatoriedad de clave via metadatos  - Corrige envio JS
=>  Fix uso factor local en toba_usuarios 

php/nucleo/toba_solicitud_web.php
Elimina escapados anidados que generan problemas
=>  Elimina escapado anidado en solicitud_web

php/nucleo/lib/salidas/toba_impr_html.php, php/nucleo/lib/salidas/toba_vista_araireportes.php, php/nucleo/lib/salidas/toba_vista_excel.php, php/nucleo/lib/salidas/toba_vista_jasperreports.php, php/nucleo/lib/salidas/toba_vista_pdf.php, php/nucleo/lib/salidas/toba_vista_xml.php, php/nucleo/lib/salidas/toba_vista_xslfo.php
Inicializa variable de clase para evitar notice
=>  Fix notices en clases impresion 

composer.json, php/nucleo/componentes/interface/toba_ei_cuadro.php, php/nucleo/componentes/interface/toba_ei_cuadro_salida_html.php, proyectos/toba_referencia/php/manejador_referencia/src/SIU/ManejadorReferencia/Componentes/Interfaz/referencia_cuadro_salida_html.php, www/js/componentes/ei.js, www/js/componentes/ei_cuadro.js
Se agrega parametro para propagar la zona en la exportacion interna de los cuadros
Fix #90
=> Exportacion de cuadro con zona

php/nucleo/componentes/interface/toba_ei_calendario.php
- Corrige seleccion de sabado y domingo
=> Fix seleccion ei_calendario

php/nucleo/lib/toba_vinculador.php
Elimina parametros con valor null del vinculo. Fix #117
=> Elimina parametros inutiles del vinculo

proyectos/toba_usuarios/php/extension_toba/toba_usuarios_modelo.php, proyectos/toba_usuarios/php/lib/admin_instancia.php, proyectos/toba_usuarios/php/lib/consultas_instancia.php, proyectos/toba_usuarios/php/perfiles/asociacion_menu/ci_asociar_menu_perfil.php, proyectos/toba_usuarios/php/perfiles/perfil_funcional/ci_navegacion_perfiles.php, proyectos/toba_usuarios/php/perfiles/restricciones_funcionales/ci_restricciones_funcionales.php, proyectos/toba_usuarios/php/servicios_web/generar_certificados/ci_gen_certificado.php, proyectos/toba_usuarios/php/servicios_web/keystore_clientes/ci_servicios_ofrecidos.php, proyectos/toba_usuarios/php/servicios_web/keystore_servidores/ci_servicios_consumidos.php, proyectos/toba_usuarios/php/servicios_web/rest/servicios_consumidos/ci_servicios_consumidos.php, proyectos/toba_usuarios/php/servicios_web/rest/servicios_ofrecidos/ci_servicios_ofrecidos.php, proyectos/toba_usuarios/php/usuarios/ci_editor.php, proyectos/toba_usuarios/php/usuarios/segundo_factor/ci_2fa_por_perfil.php
-  Agrega ID de fuente a las consultas en toba_usuarios
=> Explicita id fuente en toba_usuarios

composer.json, php/nucleo/lib/toba_manejador_sesiones.php, php/nucleo/lib/toba_memoria.php
Elimina SecurityMultitool y reemplaza la parte de CSRF con Symfony/Security/Csrf
=> Reemplazo SecurityMultiTool

proyectos/toba_usuarios/php/extension_toba/toba_usuarios_modelo.php, proyectos/toba_usuarios/php/lib/admin_instancia.php, proyectos/toba_usuarios/php/lib/consultas_instancia.php, proyectos/toba_usuarios/php/perfiles/asociacion_menu/ci_asociar_menu_perfil.php, proyectos/toba_usuarios/php/perfiles/perfil_funcional/ci_navegacion_perfiles.php, proyectos/toba_usuarios/php/perfiles/restricciones_funcionales/ci_restricciones_funcionales.php, proyectos/toba_usuarios/php/servicios_web/generar_certificados/ci_gen_certificado.php, proyectos/toba_usuarios/php/servicios_web/keystore_clientes/ci_servicios_ofrecidos.php, proyectos/toba_usuarios/php/servicios_web/keystore_servidores/ci_servicios_consumidos.php, proyectos/toba_usuarios/php/servicios_web/rest/servicios_consumidos/ci_servicios_consumidos.php, proyectos/toba_usuarios/php/servicios_web/rest/servicios_ofrecidos/ci_servicios_ofrecidos.php, proyectos/toba_usuarios/php/usuarios/ci_editor.php, proyectos/toba_usuarios/php/usuarios/segundo_factor/ci_2fa_por_perfil.php
Ajusta ID de fuente de datos, es mas simple que migrar los metadatos del proyecto de versiones previas
=>  Fix ID fuente usuarios (Related #122) 

proyectos/toba_usuarios/php/servicios_web/rest/servicios_consumidos/ci_servicios_consumidos.php
Cambia del endpoint status -> info para testear presencia de API
=>  Cambia test de presencia API Rest 

php/nucleo/lib/toba_manejador_sesiones.php
Seteo de perfil de datos activo (https://github.com/SIU-Toba/framework/issues/130)
=> Seteo de perfil de datos activo

php/modelo/ddl/pgsql_a04_tablas_log_instancia.sql, php/modelo/migraciones/toba_migracion_3_4_0.php, php/modelo/migraciones_instancia/toba_migracion_3_4_0.php
Modifica el tipo de los campos `ip` en las tablas de log para permitir guardar direcciones IPv6
Fix #96
=> Actualiza campo IP en logs 

php/nucleo/componentes/interface/efs/toba_ef_cuit.php, www/js/efs/ef_combo_editable.js, www/js/efs/ef_cuit.js
-  Agrega validacion de prefijos en ef_cuit 
-  Agrega el trimeo de valores clave para el combo_editable en JS, de lo contrario la comparacion previa al submit falla.
=>  Validacion ef_cuit 

php/consola/comandos/comando_toba.php
El hilo y la explicación se encuentra en #155
=> Problema en claves de la instalación silenciosa

php/nucleo/lib/salidas/toba_vista_jasperreports.php
Si se produce un error durante la ejecucion del reporte no se cierra correctamente la conexion JDBC
[Issue Int. 313](https://gitlab.siu.edu.ar/siu/soporte/issues/313)
=> Mejora cierre conexión DB desde Jasper

php/nucleo/lib/toba_instancia.php
Elimina la barra al final de la URL del proyecto
=>  Ajuste para correr proyectos sin alias

php/nucleo/lib/toba_rest.php
Rama que parte desde #142 y corrige los detalles marcados ahi.
=> Mejora al enviar a swagger documentacion de apis legacy

php/nucleo/componentes/interface/efs/toba_ef_cuit.php, proyectos/toba_referencia/php/componentes/uso_del_solo_lectura/ci_principal.php
Agrega posibilidad de inyectar lista de prefijos particulares para ef_cuit, mayormente por BC
=>  Permite inyectar prefijos en ef_cuit

php/consola/comandos/comando_servicios_web.php, php/modelo/toba_modelo_rest.php, php/modelo/toba_modelo_servicio_web.php, php/modelo/var/rest_cliente.ini, php/nucleo/lib/toba_servicio_web_cliente_rest.php, proyectos/toba_usuarios/php/lib/rest_arai_usuarios.php
Fija comportamiento del cliente de Api para la version via configuracion
=> Cliente de Api se fija por config

bin/toba_versionar, composer.json, package.json, php/lib/registro/toba_registro.php, php/lib/toba_xml.php, php/lib/toba_xml_tablas.php, php/nucleo/componentes/interface/efs/toba_ef_upload.php, php/nucleo/componentes/interface/toba_ei_formulario.php, php/nucleo/lib/autenticacion/toba_autenticacion_saml.php, php/nucleo/lib/autenticacion/toba_autenticacion_saml_onelogin.php, php/nucleo/lib/salidas/toba_vista_araireportes.php, php/nucleo/lib/salidas/toba_vista_jasperreports.php, php/nucleo/lib/toba_autenticacion.php, php/nucleo/lib/toba_http.php
Corrige mensajes deprecated causado por no chequear valores nulos
=>  Fix msg warning al exportar perfiles produccion

php/nucleo/lib/rest/toba_usuarios_rest_conf.php
Agrega env-var para manejar de manera comprimida las API_KEYS de los clientes
=>  Maneja API_KEYS via env-var para rest

php/modelo/lib/toba_auditoria_tablas_postgres.php
Si al momento de regenerar la auditoría hay triggers creados, pero desactivados, esta sentencia causa un error que deja al sistema momentáneamente sin auditoría.
=> Fix crear_triggers en toba_auditoria_tablas_postgres.php

php/consola/comandos/comando_base.php, php/lib/db/toba_db_postgres7.php, php/modelo/toba_modelo_instancia.php
Corrige SQL y metodo que recupera secuencias desde db
=>  Fix actualizacion secuencias
